// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: tunnel.proto

package tunnelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ServerMessage_Connected
	//	*ServerMessage_Operation
	//	*ServerMessage_Shutdown
	//	*ServerMessage_WorkspaceResult
	Kind          isServerMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *ServerMessage) GetKind() isServerMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ServerMessage) GetConnected() *Connected {
	if x != nil {
		if x, ok := x.Kind.(*ServerMessage_Connected); ok {
			return x.Connected
		}
	}
	return nil
}

func (x *ServerMessage) GetOperation() *Operation {
	if x != nil {
		if x, ok := x.Kind.(*ServerMessage_Operation); ok {
			return x.Operation
		}
	}
	return nil
}

func (x *ServerMessage) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Kind.(*ServerMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *ServerMessage) GetWorkspaceResult() *WorkspaceResult {
	if x != nil {
		if x, ok := x.Kind.(*ServerMessage_WorkspaceResult); ok {
			return x.WorkspaceResult
		}
	}
	return nil
}

type isServerMessage_Kind interface {
	isServerMessage_Kind()
}

type ServerMessage_Connected struct {
	Connected *Connected `protobuf:"bytes,1,opt,name=connected,proto3,oneof"` // first server message on success
}

type ServerMessage_Operation struct {
	Operation *Operation `protobuf:"bytes,2,opt,name=operation,proto3,oneof"`
}

type ServerMessage_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,3,opt,name=shutdown,proto3,oneof"` // terminal: revoked, superseded, or drained
}

type ServerMessage_WorkspaceResult struct {
	WorkspaceResult *WorkspaceResult `protobuf:"bytes,4,opt,name=workspace_result,json=workspaceResult,proto3,oneof"`
}

func (*ServerMessage_Connected) isServerMessage_Kind() {}

func (*ServerMessage_Operation) isServerMessage_Kind() {}

func (*ServerMessage_Shutdown) isServerMessage_Kind() {}

func (*ServerMessage_WorkspaceResult) isServerMessage_Kind() {}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Result
	//	*AgentMessage_Error
	//	*AgentMessage_Deregister
	//	*AgentMessage_WorkspaceCall
	Kind          isAgentMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *AgentMessage) GetKind() isAgentMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Kind.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetResult() *OperationResult {
	if x != nil {
		if x, ok := x.Kind.(*AgentMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *AgentMessage) GetError() *OperationError {
	if x != nil {
		if x, ok := x.Kind.(*AgentMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *AgentMessage) GetDeregister() *Deregister {
	if x != nil {
		if x, ok := x.Kind.(*AgentMessage_Deregister); ok {
			return x.Deregister
		}
	}
	return nil
}

func (x *AgentMessage) GetWorkspaceCall() *WorkspaceCall {
	if x != nil {
		if x, ok := x.Kind.(*AgentMessage_WorkspaceCall); ok {
			return x.WorkspaceCall
		}
	}
	return nil
}

type isAgentMessage_Kind interface {
	isAgentMessage_Kind()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // first agent message, always
}

type AgentMessage_Result struct {
	Result *OperationResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type AgentMessage_Error struct {
	Error *OperationError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type AgentMessage_Deregister struct {
	Deregister *Deregister `protobuf:"bytes,4,opt,name=deregister,proto3,oneof"`
}

type AgentMessage_WorkspaceCall struct {
	WorkspaceCall *WorkspaceCall `protobuf:"bytes,5,opt,name=workspace_call,json=workspaceCall,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Kind() {}

func (*AgentMessage_Result) isAgentMessage_Kind() {}

func (*AgentMessage_Error) isAgentMessage_Kind() {}

func (*AgentMessage_Deregister) isAgentMessage_Kind() {}

func (*AgentMessage_WorkspaceCall) isAgentMessage_Kind() {}

type Hello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MachineId       string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	RunAsUser       string                 `protobuf:"bytes,3,opt,name=run_as_user,json=runAsUser,proto3" json:"run_as_user,omitempty"`
	Hostname        string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OperatingSystem string                 `protobuf:"bytes,5,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	Architecture    string                 `protobuf:"bytes,6,opt,name=architecture,proto3" json:"architecture,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetRunAsUser() string {
	if x != nil {
		return x.RunAsUser
	}
	return ""
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Hello) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *Hello) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

type Connected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connected) Reset() {
	*x = Connected{}
	mi := &file_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connected) ProtoMessage() {}

func (x *Connected) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connected.ProtoReflect.Descriptor instead.
func (*Connected) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *Connected) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *Shutdown) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Deregister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deregister) Reset() {
	*x = Deregister{}
	mi := &file_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deregister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deregister) ProtoMessage() {}

func (x *Deregister) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deregister.ProtoReflect.Descriptor instead.
func (*Deregister) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{5}
}

type Operation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId  string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	SessionId      int64                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // the shell context; 0 = no session (never for agent paths)
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// Session.ShellStateGeneration — part of the shell state's identity, not metadata: a session-refresh command
	// bumps this, which changes the state directory name AND must change what the far side's served-session ledger
	// keys on, or a reset session keeps reporting IsFreshShell=false against a directory it has never touched.
	ShellStateGeneration int32 `protobuf:"varint,9,opt,name=shell_state_generation,json=shellStateGeneration,proto3" json:"shell_state_generation,omitempty"`
	// Types that are valid to be assigned to Call:
	//
	//	*Operation_RunCommand
	//	*Operation_ListDirectory
	//	*Operation_ReadFile
	//	*Operation_WriteFile
	//	*Operation_DeleteFile
	//	*Operation_InvokeHarness
	Call          isOperation_Call `protobuf_oneof:"call"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *Operation) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Operation) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *Operation) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Operation) GetShellStateGeneration() int32 {
	if x != nil {
		return x.ShellStateGeneration
	}
	return 0
}

func (x *Operation) GetCall() isOperation_Call {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *Operation) GetRunCommand() *RunCommandCall {
	if x != nil {
		if x, ok := x.Call.(*Operation_RunCommand); ok {
			return x.RunCommand
		}
	}
	return nil
}

func (x *Operation) GetListDirectory() *ListDirectoryCall {
	if x != nil {
		if x, ok := x.Call.(*Operation_ListDirectory); ok {
			return x.ListDirectory
		}
	}
	return nil
}

func (x *Operation) GetReadFile() *ReadFileCall {
	if x != nil {
		if x, ok := x.Call.(*Operation_ReadFile); ok {
			return x.ReadFile
		}
	}
	return nil
}

func (x *Operation) GetWriteFile() *WriteFileCall {
	if x != nil {
		if x, ok := x.Call.(*Operation_WriteFile); ok {
			return x.WriteFile
		}
	}
	return nil
}

func (x *Operation) GetDeleteFile() *DeleteFileCall {
	if x != nil {
		if x, ok := x.Call.(*Operation_DeleteFile); ok {
			return x.DeleteFile
		}
	}
	return nil
}

func (x *Operation) GetInvokeHarness() *InvokeHarnessCall {
	if x != nil {
		if x, ok := x.Call.(*Operation_InvokeHarness); ok {
			return x.InvokeHarness
		}
	}
	return nil
}

type isOperation_Call interface {
	isOperation_Call()
}

type Operation_RunCommand struct {
	RunCommand *RunCommandCall `protobuf:"bytes,4,opt,name=run_command,json=runCommand,proto3,oneof"`
}

type Operation_ListDirectory struct {
	ListDirectory *ListDirectoryCall `protobuf:"bytes,5,opt,name=list_directory,json=listDirectory,proto3,oneof"`
}

type Operation_ReadFile struct {
	ReadFile *ReadFileCall `protobuf:"bytes,6,opt,name=read_file,json=readFile,proto3,oneof"`
}

type Operation_WriteFile struct {
	WriteFile *WriteFileCall `protobuf:"bytes,7,opt,name=write_file,json=writeFile,proto3,oneof"`
}

type Operation_DeleteFile struct {
	DeleteFile *DeleteFileCall `protobuf:"bytes,8,opt,name=delete_file,json=deleteFile,proto3,oneof"`
}

type Operation_InvokeHarness struct {
	InvokeHarness *InvokeHarnessCall `protobuf:"bytes,10,opt,name=invoke_harness,json=invokeHarness,proto3,oneof"`
}

func (*Operation_RunCommand) isOperation_Call() {}

func (*Operation_ListDirectory) isOperation_Call() {}

func (*Operation_ReadFile) isOperation_Call() {}

func (*Operation_WriteFile) isOperation_Call() {}

func (*Operation_DeleteFile) isOperation_Call() {}

func (*Operation_InvokeHarness) isOperation_Call() {}

// `command` arrives ALREADY wrapped by SshLoginShellWrap. The daemon must NOT wrap it again; it reproduces
// sshd's exec contract, applies the session's working directory and environment, and runs it verbatim.
// `policy_match_command` is the RAW, unwrapped command text the agent asked for — carried purely so the daemon's
// local `allow_commands`/`deny_commands` policy can match against what the user actually typed, not the
// base64-wrapped shell invocation. It is NEVER executed; `command` is the only field that ever reaches shellrun.Run.
type RunCommandCall struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Command            string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	MaxOutputBytes     int32                  `protobuf:"varint,2,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	PolicyMatchCommand string                 `protobuf:"bytes,3,opt,name=policy_match_command,json=policyMatchCommand,proto3" json:"policy_match_command,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RunCommandCall) Reset() {
	*x = RunCommandCall{}
	mi := &file_tunnel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandCall) ProtoMessage() {}

func (x *RunCommandCall) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandCall.ProtoReflect.Descriptor instead.
func (*RunCommandCall) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{7}
}

func (x *RunCommandCall) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RunCommandCall) GetMaxOutputBytes() int32 {
	if x != nil {
		return x.MaxOutputBytes
	}
	return 0
}

func (x *RunCommandCall) GetPolicyMatchCommand() string {
	if x != nil {
		return x.PolicyMatchCommand
	}
	return ""
}

type ListDirectoryCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	MaxEntries    int32                  `protobuf:"varint,2,opt,name=max_entries,json=maxEntries,proto3" json:"max_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryCall) Reset() {
	*x = ListDirectoryCall{}
	mi := &file_tunnel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryCall) ProtoMessage() {}

func (x *ListDirectoryCall) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryCall.ProtoReflect.Descriptor instead.
func (*ListDirectoryCall) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{8}
}

func (x *ListDirectoryCall) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListDirectoryCall) GetMaxEntries() int32 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

type ReadFileCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	MaxBytes      int64                  `protobuf:"varint,2,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileCall) Reset() {
	*x = ReadFileCall{}
	mi := &file_tunnel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileCall) ProtoMessage() {}

func (x *ReadFileCall) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileCall.ProtoReflect.Descriptor instead.
func (*ReadFileCall) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{9}
}

func (x *ReadFileCall) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileCall) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type WriteFileCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileCall) Reset() {
	*x = WriteFileCall{}
	mi := &file_tunnel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileCall) ProtoMessage() {}

func (x *WriteFileCall) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileCall.ProtoReflect.Descriptor instead.
func (*WriteFileCall) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{10}
}

func (x *WriteFileCall) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileCall) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type DeleteFileCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileCall) Reset() {
	*x = DeleteFileCall{}
	mi := &file_tunnel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileCall) ProtoMessage() {}

func (x *DeleteFileCall) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileCall.ProtoReflect.Descriptor instead.
func (*DeleteFileCall) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteFileCall) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// The daemon resolves `harness` from its OWN local config/defaults only — the platform never sends a URL, path,
// flag, or argv fragment (no SSRF/exec pivot). An invocation MUST be side-effect-free on the box: CLI harnesses
// are always run pinned to non-agentic, tool-free modes by the daemon's fixed argv, never the box's local config.
type InvokeHarnessCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Harness       string                 `protobuf:"bytes,1,opt,name=harness,proto3" json:"harness,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeHarnessCall) Reset() {
	*x = InvokeHarnessCall{}
	mi := &file_tunnel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeHarnessCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeHarnessCall) ProtoMessage() {}

func (x *InvokeHarnessCall) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeHarnessCall.ProtoReflect.Descriptor instead.
func (*InvokeHarnessCall) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{12}
}

func (x *InvokeHarnessCall) GetHarness() string {
	if x != nil {
		return x.Harness
	}
	return ""
}

func (x *InvokeHarnessCall) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *InvokeHarnessCall) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type OperationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	IsFreshShell  bool                   `protobuf:"varint,2,opt,name=is_fresh_shell,json=isFreshShell,proto3" json:"is_fresh_shell,omitempty"` // a context was CREATED, not resumed — surfaced to the model
	// Types that are valid to be assigned to Result:
	//
	//	*OperationResult_RunCommand
	//	*OperationResult_ListDirectory
	//	*OperationResult_ReadFile
	//	*OperationResult_WriteFile
	//	*OperationResult_DeleteFile
	//	*OperationResult_InvokeHarness
	Result        isOperationResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResult) Reset() {
	*x = OperationResult{}
	mi := &file_tunnel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResult) ProtoMessage() {}

func (x *OperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResult.ProtoReflect.Descriptor instead.
func (*OperationResult) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{13}
}

func (x *OperationResult) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *OperationResult) GetIsFreshShell() bool {
	if x != nil {
		return x.IsFreshShell
	}
	return false
}

func (x *OperationResult) GetResult() isOperationResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *OperationResult) GetRunCommand() *RunCommandResult {
	if x != nil {
		if x, ok := x.Result.(*OperationResult_RunCommand); ok {
			return x.RunCommand
		}
	}
	return nil
}

func (x *OperationResult) GetListDirectory() *ListDirectoryResult {
	if x != nil {
		if x, ok := x.Result.(*OperationResult_ListDirectory); ok {
			return x.ListDirectory
		}
	}
	return nil
}

func (x *OperationResult) GetReadFile() *ReadFileResult {
	if x != nil {
		if x, ok := x.Result.(*OperationResult_ReadFile); ok {
			return x.ReadFile
		}
	}
	return nil
}

func (x *OperationResult) GetWriteFile() *WriteFileResult {
	if x != nil {
		if x, ok := x.Result.(*OperationResult_WriteFile); ok {
			return x.WriteFile
		}
	}
	return nil
}

func (x *OperationResult) GetDeleteFile() *DeleteFileResult {
	if x != nil {
		if x, ok := x.Result.(*OperationResult_DeleteFile); ok {
			return x.DeleteFile
		}
	}
	return nil
}

func (x *OperationResult) GetInvokeHarness() *InvokeHarnessResult {
	if x != nil {
		if x, ok := x.Result.(*OperationResult_InvokeHarness); ok {
			return x.InvokeHarness
		}
	}
	return nil
}

type isOperationResult_Result interface {
	isOperationResult_Result()
}

type OperationResult_RunCommand struct {
	RunCommand *RunCommandResult `protobuf:"bytes,3,opt,name=run_command,json=runCommand,proto3,oneof"`
}

type OperationResult_ListDirectory struct {
	ListDirectory *ListDirectoryResult `protobuf:"bytes,4,opt,name=list_directory,json=listDirectory,proto3,oneof"`
}

type OperationResult_ReadFile struct {
	ReadFile *ReadFileResult `protobuf:"bytes,5,opt,name=read_file,json=readFile,proto3,oneof"`
}

type OperationResult_WriteFile struct {
	WriteFile *WriteFileResult `protobuf:"bytes,6,opt,name=write_file,json=writeFile,proto3,oneof"`
}

type OperationResult_DeleteFile struct {
	DeleteFile *DeleteFileResult `protobuf:"bytes,7,opt,name=delete_file,json=deleteFile,proto3,oneof"`
}

type OperationResult_InvokeHarness struct {
	InvokeHarness *InvokeHarnessResult `protobuf:"bytes,8,opt,name=invoke_harness,json=invokeHarness,proto3,oneof"`
}

func (*OperationResult_RunCommand) isOperationResult_Result() {}

func (*OperationResult_ListDirectory) isOperationResult_Result() {}

func (*OperationResult_ReadFile) isOperationResult_Result() {}

func (*OperationResult_WriteFile) isOperationResult_Result() {}

func (*OperationResult_DeleteFile) isOperationResult_Result() {}

func (*OperationResult_InvokeHarness) isOperationResult_Result() {}

type RunCommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	ErrorOutput   string                 `protobuf:"bytes,3,opt,name=error_output,json=errorOutput,proto3" json:"error_output,omitempty"`
	IsTruncated   bool                   `protobuf:"varint,4,opt,name=is_truncated,json=isTruncated,proto3" json:"is_truncated,omitempty"`
	DurationMs    int32                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommandResult) Reset() {
	*x = RunCommandResult{}
	mi := &file_tunnel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandResult) ProtoMessage() {}

func (x *RunCommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandResult.ProtoReflect.Descriptor instead.
func (*RunCommandResult) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{14}
}

func (x *RunCommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunCommandResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RunCommandResult) GetErrorOutput() string {
	if x != nil {
		return x.ErrorOutput
	}
	return ""
}

func (x *RunCommandResult) GetIsTruncated() bool {
	if x != nil {
		return x.IsTruncated
	}
	return false
}

func (x *RunCommandResult) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ListDirectoryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Entries       []*DirectoryEntry      `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	IsTruncated   bool                   `protobuf:"varint,3,opt,name=is_truncated,json=isTruncated,proto3" json:"is_truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryResult) Reset() {
	*x = ListDirectoryResult{}
	mi := &file_tunnel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryResult) ProtoMessage() {}

func (x *ListDirectoryResult) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryResult.ProtoReflect.Descriptor instead.
func (*ListDirectoryResult) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{15}
}

func (x *ListDirectoryResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListDirectoryResult) GetEntries() []*DirectoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListDirectoryResult) GetIsTruncated() bool {
	if x != nil {
		return x.IsTruncated
	}
	return false
}

type DirectoryEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDirectory    bool                   `protobuf:"varint,2,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ModifiedUnixMs int64                  `protobuf:"varint,4,opt,name=modified_unix_ms,json=modifiedUnixMs,proto3" json:"modified_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DirectoryEntry) Reset() {
	*x = DirectoryEntry{}
	mi := &file_tunnel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryEntry) ProtoMessage() {}

func (x *DirectoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryEntry.ProtoReflect.Descriptor instead.
func (*DirectoryEntry) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{16}
}

func (x *DirectoryEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirectoryEntry) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *DirectoryEntry) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *DirectoryEntry) GetModifiedUnixMs() int64 {
	if x != nil {
		return x.ModifiedUnixMs
	}
	return 0
}

type ReadFileResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	IsTooLarge    bool                   `protobuf:"varint,3,opt,name=is_too_large,json=isTooLarge,proto3" json:"is_too_large,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResult) Reset() {
	*x = ReadFileResult{}
	mi := &file_tunnel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResult) ProtoMessage() {}

func (x *ReadFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResult.ProtoReflect.Descriptor instead.
func (*ReadFileResult) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{17}
}

func (x *ReadFileResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileResult) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ReadFileResult) GetIsTooLarge() bool {
	if x != nil {
		return x.IsTooLarge
	}
	return false
}

func (x *ReadFileResult) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type WriteFileResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResult) Reset() {
	*x = WriteFileResult{}
	mi := &file_tunnel_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResult) ProtoMessage() {}

func (x *WriteFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResult.ProtoReflect.Descriptor instead.
func (*WriteFileResult) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{18}
}

type DeleteFileResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResult) Reset() {
	*x = DeleteFileResult{}
	mi := &file_tunnel_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResult) ProtoMessage() {}

func (x *DeleteFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResult.ProtoReflect.Descriptor instead.
func (*DeleteFileResult) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{19}
}

// status_code is the local HTTP status (server family) or process exit code (CLI family) — NOT a uniform
// "0 is good" convention across families; payload is stdout / response body verbatim — the daemon never
// interprets it, C# owns all interpretation.
type InvokeHarnessResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ErrorOutput   string                 `protobuf:"bytes,3,opt,name=error_output,json=errorOutput,proto3" json:"error_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeHarnessResult) Reset() {
	*x = InvokeHarnessResult{}
	mi := &file_tunnel_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeHarnessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeHarnessResult) ProtoMessage() {}

func (x *InvokeHarnessResult) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeHarnessResult.ProtoReflect.Descriptor instead.
func (*InvokeHarnessResult) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{20}
}

func (x *InvokeHarnessResult) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *InvokeHarnessResult) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *InvokeHarnessResult) GetErrorOutput() string {
	if x != nil {
		return x.ErrorOutput
	}
	return ""
}

// code mirrors SshOperationException.Code exactly, plus the connect-time codes the egress adds:
// file_not_found | permission_denied | is_directory | timeout | too_large | policy_denied |
// connect_failed | host_key_mismatch | blocked_address | not_connected | internal | harness_unavailable
type OperationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationError) Reset() {
	*x = OperationError{}
	mi := &file_tunnel_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationError) ProtoMessage() {}

func (x *OperationError) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationError.ProtoReflect.Descriptor instead.
func (*OperationError) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{21}
}

func (x *OperationError) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *OperationError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OperationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Host-initiated workspace bridge (the `agentparley ws` subcommand). Unlike Operation (platform-initiated), these
// originate on the host: a command running on the box asks the platform for a presigned URL to read/write a
// workspace file. The bytes themselves travel host<->S3 directly on that URL; only these tiny control messages ride
// the tunnel. session_id is a non-secret default-agent hint (0 = a human shell with no session); agent_selector
// (agent id or slug) overrides it, always resolved within THIS host's account server-side.
type WorkspaceCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	SessionId     int64                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`            // 0 = no session context (a human shell)
	AgentSelector string                 `protobuf:"bytes,3,opt,name=agent_selector,json=agentSelector,proto3" json:"agent_selector,omitempty"` // "" = default to the session's agent; else agent id or slug
	// Types that are valid to be assigned to Op:
	//
	//	*WorkspaceCall_ReadOpen
	//	*WorkspaceCall_WriteBegin
	//	*WorkspaceCall_WriteCommit
	Op            isWorkspaceCall_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceCall) Reset() {
	*x = WorkspaceCall{}
	mi := &file_tunnel_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceCall) ProtoMessage() {}

func (x *WorkspaceCall) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceCall.ProtoReflect.Descriptor instead.
func (*WorkspaceCall) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{22}
}

func (x *WorkspaceCall) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *WorkspaceCall) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *WorkspaceCall) GetAgentSelector() string {
	if x != nil {
		return x.AgentSelector
	}
	return ""
}

func (x *WorkspaceCall) GetOp() isWorkspaceCall_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *WorkspaceCall) GetReadOpen() *WorkspaceReadOpen {
	if x != nil {
		if x, ok := x.Op.(*WorkspaceCall_ReadOpen); ok {
			return x.ReadOpen
		}
	}
	return nil
}

func (x *WorkspaceCall) GetWriteBegin() *WorkspaceWriteBegin {
	if x != nil {
		if x, ok := x.Op.(*WorkspaceCall_WriteBegin); ok {
			return x.WriteBegin
		}
	}
	return nil
}

func (x *WorkspaceCall) GetWriteCommit() *WorkspaceWriteCommit {
	if x != nil {
		if x, ok := x.Op.(*WorkspaceCall_WriteCommit); ok {
			return x.WriteCommit
		}
	}
	return nil
}

type isWorkspaceCall_Op interface {
	isWorkspaceCall_Op()
}

type WorkspaceCall_ReadOpen struct {
	ReadOpen *WorkspaceReadOpen `protobuf:"bytes,4,opt,name=read_open,json=readOpen,proto3,oneof"`
}

type WorkspaceCall_WriteBegin struct {
	WriteBegin *WorkspaceWriteBegin `protobuf:"bytes,5,opt,name=write_begin,json=writeBegin,proto3,oneof"`
}

type WorkspaceCall_WriteCommit struct {
	WriteCommit *WorkspaceWriteCommit `protobuf:"bytes,6,opt,name=write_commit,json=writeCommit,proto3,oneof"`
}

func (*WorkspaceCall_ReadOpen) isWorkspaceCall_Op() {}

func (*WorkspaceCall_WriteBegin) isWorkspaceCall_Op() {}

func (*WorkspaceCall_WriteCommit) isWorkspaceCall_Op() {}

type WorkspaceReadOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceReadOpen) Reset() {
	*x = WorkspaceReadOpen{}
	mi := &file_tunnel_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceReadOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceReadOpen) ProtoMessage() {}

func (x *WorkspaceReadOpen) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceReadOpen.ProtoReflect.Descriptor instead.
func (*WorkspaceReadOpen) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{23}
}

func (x *WorkspaceReadOpen) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type WorkspaceWriteBegin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceWriteBegin) Reset() {
	*x = WorkspaceWriteBegin{}
	mi := &file_tunnel_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceWriteBegin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceWriteBegin) ProtoMessage() {}

func (x *WorkspaceWriteBegin) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceWriteBegin.ProtoReflect.Descriptor instead.
func (*WorkspaceWriteBegin) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{24}
}

func (x *WorkspaceWriteBegin) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WorkspaceWriteBegin) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type WorkspaceWriteCommit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	UploadToken   int64                  `protobuf:"varint,2,opt,name=upload_token,json=uploadToken,proto3" json:"upload_token,omitempty"`
	ContentHash   string                 `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceWriteCommit) Reset() {
	*x = WorkspaceWriteCommit{}
	mi := &file_tunnel_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceWriteCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceWriteCommit) ProtoMessage() {}

func (x *WorkspaceWriteCommit) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceWriteCommit.ProtoReflect.Descriptor instead.
func (*WorkspaceWriteCommit) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{25}
}

func (x *WorkspaceWriteCommit) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WorkspaceWriteCommit) GetUploadToken() int64 {
	if x != nil {
		return x.UploadToken
	}
	return 0
}

func (x *WorkspaceWriteCommit) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

type WorkspaceResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*WorkspaceResult_ReadTarget
	//	*WorkspaceResult_WriteTarget
	//	*WorkspaceResult_Committed
	//	*WorkspaceResult_Error
	Outcome       isWorkspaceResult_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceResult) Reset() {
	*x = WorkspaceResult{}
	mi := &file_tunnel_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceResult) ProtoMessage() {}

func (x *WorkspaceResult) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceResult.ProtoReflect.Descriptor instead.
func (*WorkspaceResult) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{26}
}

func (x *WorkspaceResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *WorkspaceResult) GetOutcome() isWorkspaceResult_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *WorkspaceResult) GetReadTarget() *WorkspaceReadTarget {
	if x != nil {
		if x, ok := x.Outcome.(*WorkspaceResult_ReadTarget); ok {
			return x.ReadTarget
		}
	}
	return nil
}

func (x *WorkspaceResult) GetWriteTarget() *WorkspaceWriteTarget {
	if x != nil {
		if x, ok := x.Outcome.(*WorkspaceResult_WriteTarget); ok {
			return x.WriteTarget
		}
	}
	return nil
}

func (x *WorkspaceResult) GetCommitted() *WorkspaceCommitted {
	if x != nil {
		if x, ok := x.Outcome.(*WorkspaceResult_Committed); ok {
			return x.Committed
		}
	}
	return nil
}

func (x *WorkspaceResult) GetError() *WorkspaceCallError {
	if x != nil {
		if x, ok := x.Outcome.(*WorkspaceResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isWorkspaceResult_Outcome interface {
	isWorkspaceResult_Outcome()
}

type WorkspaceResult_ReadTarget struct {
	ReadTarget *WorkspaceReadTarget `protobuf:"bytes,2,opt,name=read_target,json=readTarget,proto3,oneof"`
}

type WorkspaceResult_WriteTarget struct {
	WriteTarget *WorkspaceWriteTarget `protobuf:"bytes,3,opt,name=write_target,json=writeTarget,proto3,oneof"`
}

type WorkspaceResult_Committed struct {
	Committed *WorkspaceCommitted `protobuf:"bytes,4,opt,name=committed,proto3,oneof"`
}

type WorkspaceResult_Error struct {
	Error *WorkspaceCallError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*WorkspaceResult_ReadTarget) isWorkspaceResult_Outcome() {}

func (*WorkspaceResult_WriteTarget) isWorkspaceResult_Outcome() {}

func (*WorkspaceResult_Committed) isWorkspaceResult_Outcome() {}

func (*WorkspaceResult_Error) isWorkspaceResult_Outcome() {}

type WorkspaceReadTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceReadTarget) Reset() {
	*x = WorkspaceReadTarget{}
	mi := &file_tunnel_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceReadTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceReadTarget) ProtoMessage() {}

func (x *WorkspaceReadTarget) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceReadTarget.ProtoReflect.Descriptor instead.
func (*WorkspaceReadTarget) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{27}
}

func (x *WorkspaceReadTarget) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type WorkspaceWriteTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UploadToken   int64                  `protobuf:"varint,3,opt,name=upload_token,json=uploadToken,proto3" json:"upload_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceWriteTarget) Reset() {
	*x = WorkspaceWriteTarget{}
	mi := &file_tunnel_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceWriteTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceWriteTarget) ProtoMessage() {}

func (x *WorkspaceWriteTarget) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceWriteTarget.ProtoReflect.Descriptor instead.
func (*WorkspaceWriteTarget) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{28}
}

func (x *WorkspaceWriteTarget) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WorkspaceWriteTarget) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *WorkspaceWriteTarget) GetUploadToken() int64 {
	if x != nil {
		return x.UploadToken
	}
	return 0
}

type WorkspaceCommitted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayPath   string                 `protobuf:"bytes,1,opt,name=display_path,json=displayPath,proto3" json:"display_path,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceCommitted) Reset() {
	*x = WorkspaceCommitted{}
	mi := &file_tunnel_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceCommitted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceCommitted) ProtoMessage() {}

func (x *WorkspaceCommitted) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceCommitted.ProtoReflect.Descriptor instead.
func (*WorkspaceCommitted) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{29}
}

func (x *WorkspaceCommitted) GetDisplayPath() string {
	if x != nil {
		return x.DisplayPath
	}
	return ""
}

func (x *WorkspaceCommitted) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// codes: unknown_host | no_agent | agent_not_found | session_not_found | invalid_path | file_not_found |
//
//	too_large | storage_limit | conflict | upload_invalid | not_connected | timeout | internal
type WorkspaceCallError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceCallError) Reset() {
	*x = WorkspaceCallError{}
	mi := &file_tunnel_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceCallError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceCallError) ProtoMessage() {}

func (x *WorkspaceCallError) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceCallError.ProtoReflect.Descriptor instead.
func (*WorkspaceCallError) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{30}
}

func (x *WorkspaceCallError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *WorkspaceCallError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_tunnel_proto protoreflect.FileDescriptor

const file_tunnel_proto_rawDesc = "" +
	"\n" +
	"\ftunnel.proto\x12\x15agentparley.tunnel.v1\"\xaf\x02\n" +
	"\rServerMessage\x12@\n" +
	"\tconnected\x18\x01 \x01(\v2 .agentparley.tunnel.v1.ConnectedH\x00R\tconnected\x12@\n" +
	"\toperation\x18\x02 \x01(\v2 .agentparley.tunnel.v1.OperationH\x00R\toperation\x12=\n" +
	"\bshutdown\x18\x03 \x01(\v2\x1f.agentparley.tunnel.v1.ShutdownH\x00R\bshutdown\x12S\n" +
	"\x10workspace_result\x18\x04 \x01(\v2&.agentparley.tunnel.v1.WorkspaceResultH\x00R\x0fworkspaceResultB\x06\n" +
	"\x04kind\"\xe1\x02\n" +
	"\fAgentMessage\x124\n" +
	"\x05hello\x18\x01 \x01(\v2\x1c.agentparley.tunnel.v1.HelloH\x00R\x05hello\x12@\n" +
	"\x06result\x18\x02 \x01(\v2&.agentparley.tunnel.v1.OperationResultH\x00R\x06result\x12=\n" +
	"\x05error\x18\x03 \x01(\v2%.agentparley.tunnel.v1.OperationErrorH\x00R\x05error\x12C\n" +
	"\n" +
	"deregister\x18\x04 \x01(\v2!.agentparley.tunnel.v1.DeregisterH\x00R\n" +
	"deregister\x12M\n" +
	"\x0eworkspace_call\x18\x05 \x01(\v2$.agentparley.tunnel.v1.WorkspaceCallH\x00R\rworkspaceCallB\x06\n" +
	"\x04kind\"\xd6\x01\n" +
	"\x05Hello\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12\x1e\n" +
	"\vrun_as_user\x18\x03 \x01(\tR\trunAsUser\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12)\n" +
	"\x10operating_system\x18\x05 \x01(\tR\x0foperatingSystem\x12\"\n" +
	"\farchitecture\x18\x06 \x01(\tR\farchitecture\"0\n" +
	"\tConnected\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"\"\n" +
	"\bShutdown\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\f\n" +
	"\n" +
	"Deregister\"\xfd\x04\n" +
	"\tOperation\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\x124\n" +
	"\x16shell_state_generation\x18\t \x01(\x05R\x14shellStateGeneration\x12H\n" +
	"\vrun_command\x18\x04 \x01(\v2%.agentparley.tunnel.v1.RunCommandCallH\x00R\n" +
	"runCommand\x12Q\n" +
	"\x0elist_directory\x18\x05 \x01(\v2(.agentparley.tunnel.v1.ListDirectoryCallH\x00R\rlistDirectory\x12B\n" +
	"\tread_file\x18\x06 \x01(\v2#.agentparley.tunnel.v1.ReadFileCallH\x00R\breadFile\x12E\n" +
	"\n" +
	"write_file\x18\a \x01(\v2$.agentparley.tunnel.v1.WriteFileCallH\x00R\twriteFile\x12H\n" +
	"\vdelete_file\x18\b \x01(\v2%.agentparley.tunnel.v1.DeleteFileCallH\x00R\n" +
	"deleteFile\x12Q\n" +
	"\x0einvoke_harness\x18\n" +
	" \x01(\v2(.agentparley.tunnel.v1.InvokeHarnessCallH\x00R\rinvokeHarnessB\x06\n" +
	"\x04call\"\x86\x01\n" +
	"\x0eRunCommandCall\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12(\n" +
	"\x10max_output_bytes\x18\x02 \x01(\x05R\x0emaxOutputBytes\x120\n" +
	"\x14policy_match_command\x18\x03 \x01(\tR\x12policyMatchCommand\"H\n" +
	"\x11ListDirectoryCall\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vmax_entries\x18\x02 \x01(\x05R\n" +
	"maxEntries\"?\n" +
	"\fReadFileCall\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tmax_bytes\x18\x02 \x01(\x03R\bmaxBytes\"=\n" +
	"\rWriteFileCall\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"$\n" +
	"\x0eDeleteFileCall\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"]\n" +
	"\x11InvokeHarnessCall\x12\x18\n" +
	"\aharness\x18\x01 \x01(\tR\aharness\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"\xb9\x04\n" +
	"\x0fOperationResult\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12$\n" +
	"\x0eis_fresh_shell\x18\x02 \x01(\bR\fisFreshShell\x12J\n" +
	"\vrun_command\x18\x03 \x01(\v2'.agentparley.tunnel.v1.RunCommandResultH\x00R\n" +
	"runCommand\x12S\n" +
	"\x0elist_directory\x18\x04 \x01(\v2*.agentparley.tunnel.v1.ListDirectoryResultH\x00R\rlistDirectory\x12D\n" +
	"\tread_file\x18\x05 \x01(\v2%.agentparley.tunnel.v1.ReadFileResultH\x00R\breadFile\x12G\n" +
	"\n" +
	"write_file\x18\x06 \x01(\v2&.agentparley.tunnel.v1.WriteFileResultH\x00R\twriteFile\x12J\n" +
	"\vdelete_file\x18\a \x01(\v2'.agentparley.tunnel.v1.DeleteFileResultH\x00R\n" +
	"deleteFile\x12S\n" +
	"\x0einvoke_harness\x18\b \x01(\v2*.agentparley.tunnel.v1.InvokeHarnessResultH\x00R\rinvokeHarnessB\b\n" +
	"\x06result\"\xae\x01\n" +
	"\x10RunCommandResult\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12!\n" +
	"\ferror_output\x18\x03 \x01(\tR\verrorOutput\x12!\n" +
	"\fis_truncated\x18\x04 \x01(\bR\visTruncated\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x05R\n" +
	"durationMs\"\x8d\x01\n" +
	"\x13ListDirectoryResult\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12?\n" +
	"\aentries\x18\x02 \x03(\v2%.agentparley.tunnel.v1.DirectoryEntryR\aentries\x12!\n" +
	"\fis_truncated\x18\x03 \x01(\bR\visTruncated\"\x90\x01\n" +
	"\x0eDirectoryEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fis_directory\x18\x02 \x01(\bR\visDirectory\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12(\n" +
	"\x10modified_unix_ms\x18\x04 \x01(\x03R\x0emodifiedUnixMs\"\x7f\n" +
	"\x0eReadFileResult\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12 \n" +
	"\fis_too_large\x18\x03 \x01(\bR\n" +
	"isTooLarge\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\"\x11\n" +
	"\x0fWriteFileResult\"\x12\n" +
	"\x10DeleteFileResult\"s\n" +
	"\x13InvokeHarnessResult\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12!\n" +
	"\ferror_output\x18\x03 \x01(\tR\verrorOutput\"e\n" +
	"\x0eOperationError\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xde\x02\n" +
	"\rWorkspaceCall\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\x12%\n" +
	"\x0eagent_selector\x18\x03 \x01(\tR\ragentSelector\x12G\n" +
	"\tread_open\x18\x04 \x01(\v2(.agentparley.tunnel.v1.WorkspaceReadOpenH\x00R\breadOpen\x12M\n" +
	"\vwrite_begin\x18\x05 \x01(\v2*.agentparley.tunnel.v1.WorkspaceWriteBeginH\x00R\n" +
	"writeBegin\x12P\n" +
	"\fwrite_commit\x18\x06 \x01(\v2+.agentparley.tunnel.v1.WorkspaceWriteCommitH\x00R\vwriteCommitB\x04\n" +
	"\x02op\"'\n" +
	"\x11WorkspaceReadOpen\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"H\n" +
	"\x13WorkspaceWriteBegin\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\"p\n" +
	"\x14WorkspaceWriteCommit\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\fupload_token\x18\x02 \x01(\x03R\vuploadToken\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\tR\vcontentHash\"\xe4\x02\n" +
	"\x0fWorkspaceResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12M\n" +
	"\vread_target\x18\x02 \x01(\v2*.agentparley.tunnel.v1.WorkspaceReadTargetH\x00R\n" +
	"readTarget\x12P\n" +
	"\fwrite_target\x18\x03 \x01(\v2+.agentparley.tunnel.v1.WorkspaceWriteTargetH\x00R\vwriteTarget\x12I\n" +
	"\tcommitted\x18\x04 \x01(\v2).agentparley.tunnel.v1.WorkspaceCommittedH\x00R\tcommitted\x12A\n" +
	"\x05error\x18\x05 \x01(\v2).agentparley.tunnel.v1.WorkspaceCallErrorH\x00R\x05errorB\t\n" +
	"\aoutcome\"'\n" +
	"\x13WorkspaceReadTarget\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xd7\x01\n" +
	"\x14WorkspaceWriteTarget\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12O\n" +
	"\x06fields\x18\x02 \x03(\v27.agentparley.tunnel.v1.WorkspaceWriteTarget.FieldsEntryR\x06fields\x12!\n" +
	"\fupload_token\x18\x03 \x01(\x03R\vuploadToken\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"V\n" +
	"\x12WorkspaceCommitted\x12!\n" +
	"\fdisplay_path\x18\x01 \x01(\tR\vdisplayPath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\"B\n" +
	"\x12WorkspaceCallError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2i\n" +
	"\rTunnelService\x12X\n" +
	"\aConnect\x12#.agentparley.tunnel.v1.AgentMessage\x1a$.agentparley.tunnel.v1.ServerMessage(\x010\x01BZZ5github.com/agentparley/tunnel/internal/proto;tunnelpb\xaa\x02 AgentParley.Cloud.SshEgress.Grpcb\x06proto3"

var (
	file_tunnel_proto_rawDescOnce sync.Once
	file_tunnel_proto_rawDescData []byte
)

func file_tunnel_proto_rawDescGZIP() []byte {
	file_tunnel_proto_rawDescOnce.Do(func() {
		file_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tunnel_proto_rawDesc), len(file_tunnel_proto_rawDesc)))
	})
	return file_tunnel_proto_rawDescData
}

var file_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_tunnel_proto_goTypes = []any{
	(*ServerMessage)(nil),        // 0: agentparley.tunnel.v1.ServerMessage
	(*AgentMessage)(nil),         // 1: agentparley.tunnel.v1.AgentMessage
	(*Hello)(nil),                // 2: agentparley.tunnel.v1.Hello
	(*Connected)(nil),            // 3: agentparley.tunnel.v1.Connected
	(*Shutdown)(nil),             // 4: agentparley.tunnel.v1.Shutdown
	(*Deregister)(nil),           // 5: agentparley.tunnel.v1.Deregister
	(*Operation)(nil),            // 6: agentparley.tunnel.v1.Operation
	(*RunCommandCall)(nil),       // 7: agentparley.tunnel.v1.RunCommandCall
	(*ListDirectoryCall)(nil),    // 8: agentparley.tunnel.v1.ListDirectoryCall
	(*ReadFileCall)(nil),         // 9: agentparley.tunnel.v1.ReadFileCall
	(*WriteFileCall)(nil),        // 10: agentparley.tunnel.v1.WriteFileCall
	(*DeleteFileCall)(nil),       // 11: agentparley.tunnel.v1.DeleteFileCall
	(*InvokeHarnessCall)(nil),    // 12: agentparley.tunnel.v1.InvokeHarnessCall
	(*OperationResult)(nil),      // 13: agentparley.tunnel.v1.OperationResult
	(*RunCommandResult)(nil),     // 14: agentparley.tunnel.v1.RunCommandResult
	(*ListDirectoryResult)(nil),  // 15: agentparley.tunnel.v1.ListDirectoryResult
	(*DirectoryEntry)(nil),       // 16: agentparley.tunnel.v1.DirectoryEntry
	(*ReadFileResult)(nil),       // 17: agentparley.tunnel.v1.ReadFileResult
	(*WriteFileResult)(nil),      // 18: agentparley.tunnel.v1.WriteFileResult
	(*DeleteFileResult)(nil),     // 19: agentparley.tunnel.v1.DeleteFileResult
	(*InvokeHarnessResult)(nil),  // 20: agentparley.tunnel.v1.InvokeHarnessResult
	(*OperationError)(nil),       // 21: agentparley.tunnel.v1.OperationError
	(*WorkspaceCall)(nil),        // 22: agentparley.tunnel.v1.WorkspaceCall
	(*WorkspaceReadOpen)(nil),    // 23: agentparley.tunnel.v1.WorkspaceReadOpen
	(*WorkspaceWriteBegin)(nil),  // 24: agentparley.tunnel.v1.WorkspaceWriteBegin
	(*WorkspaceWriteCommit)(nil), // 25: agentparley.tunnel.v1.WorkspaceWriteCommit
	(*WorkspaceResult)(nil),      // 26: agentparley.tunnel.v1.WorkspaceResult
	(*WorkspaceReadTarget)(nil),  // 27: agentparley.tunnel.v1.WorkspaceReadTarget
	(*WorkspaceWriteTarget)(nil), // 28: agentparley.tunnel.v1.WorkspaceWriteTarget
	(*WorkspaceCommitted)(nil),   // 29: agentparley.tunnel.v1.WorkspaceCommitted
	(*WorkspaceCallError)(nil),   // 30: agentparley.tunnel.v1.WorkspaceCallError
	nil,                          // 31: agentparley.tunnel.v1.WorkspaceWriteTarget.FieldsEntry
}
var file_tunnel_proto_depIdxs = []int32{
	3,  // 0: agentparley.tunnel.v1.ServerMessage.connected:type_name -> agentparley.tunnel.v1.Connected
	6,  // 1: agentparley.tunnel.v1.ServerMessage.operation:type_name -> agentparley.tunnel.v1.Operation
	4,  // 2: agentparley.tunnel.v1.ServerMessage.shutdown:type_name -> agentparley.tunnel.v1.Shutdown
	26, // 3: agentparley.tunnel.v1.ServerMessage.workspace_result:type_name -> agentparley.tunnel.v1.WorkspaceResult
	2,  // 4: agentparley.tunnel.v1.AgentMessage.hello:type_name -> agentparley.tunnel.v1.Hello
	13, // 5: agentparley.tunnel.v1.AgentMessage.result:type_name -> agentparley.tunnel.v1.OperationResult
	21, // 6: agentparley.tunnel.v1.AgentMessage.error:type_name -> agentparley.tunnel.v1.OperationError
	5,  // 7: agentparley.tunnel.v1.AgentMessage.deregister:type_name -> agentparley.tunnel.v1.Deregister
	22, // 8: agentparley.tunnel.v1.AgentMessage.workspace_call:type_name -> agentparley.tunnel.v1.WorkspaceCall
	7,  // 9: agentparley.tunnel.v1.Operation.run_command:type_name -> agentparley.tunnel.v1.RunCommandCall
	8,  // 10: agentparley.tunnel.v1.Operation.list_directory:type_name -> agentparley.tunnel.v1.ListDirectoryCall
	9,  // 11: agentparley.tunnel.v1.Operation.read_file:type_name -> agentparley.tunnel.v1.ReadFileCall
	10, // 12: agentparley.tunnel.v1.Operation.write_file:type_name -> agentparley.tunnel.v1.WriteFileCall
	11, // 13: agentparley.tunnel.v1.Operation.delete_file:type_name -> agentparley.tunnel.v1.DeleteFileCall
	12, // 14: agentparley.tunnel.v1.Operation.invoke_harness:type_name -> agentparley.tunnel.v1.InvokeHarnessCall
	14, // 15: agentparley.tunnel.v1.OperationResult.run_command:type_name -> agentparley.tunnel.v1.RunCommandResult
	15, // 16: agentparley.tunnel.v1.OperationResult.list_directory:type_name -> agentparley.tunnel.v1.ListDirectoryResult
	17, // 17: agentparley.tunnel.v1.OperationResult.read_file:type_name -> agentparley.tunnel.v1.ReadFileResult
	18, // 18: agentparley.tunnel.v1.OperationResult.write_file:type_name -> agentparley.tunnel.v1.WriteFileResult
	19, // 19: agentparley.tunnel.v1.OperationResult.delete_file:type_name -> agentparley.tunnel.v1.DeleteFileResult
	20, // 20: agentparley.tunnel.v1.OperationResult.invoke_harness:type_name -> agentparley.tunnel.v1.InvokeHarnessResult
	16, // 21: agentparley.tunnel.v1.ListDirectoryResult.entries:type_name -> agentparley.tunnel.v1.DirectoryEntry
	23, // 22: agentparley.tunnel.v1.WorkspaceCall.read_open:type_name -> agentparley.tunnel.v1.WorkspaceReadOpen
	24, // 23: agentparley.tunnel.v1.WorkspaceCall.write_begin:type_name -> agentparley.tunnel.v1.WorkspaceWriteBegin
	25, // 24: agentparley.tunnel.v1.WorkspaceCall.write_commit:type_name -> agentparley.tunnel.v1.WorkspaceWriteCommit
	27, // 25: agentparley.tunnel.v1.WorkspaceResult.read_target:type_name -> agentparley.tunnel.v1.WorkspaceReadTarget
	28, // 26: agentparley.tunnel.v1.WorkspaceResult.write_target:type_name -> agentparley.tunnel.v1.WorkspaceWriteTarget
	29, // 27: agentparley.tunnel.v1.WorkspaceResult.committed:type_name -> agentparley.tunnel.v1.WorkspaceCommitted
	30, // 28: agentparley.tunnel.v1.WorkspaceResult.error:type_name -> agentparley.tunnel.v1.WorkspaceCallError
	31, // 29: agentparley.tunnel.v1.WorkspaceWriteTarget.fields:type_name -> agentparley.tunnel.v1.WorkspaceWriteTarget.FieldsEntry
	1,  // 30: agentparley.tunnel.v1.TunnelService.Connect:input_type -> agentparley.tunnel.v1.AgentMessage
	0,  // 31: agentparley.tunnel.v1.TunnelService.Connect:output_type -> agentparley.tunnel.v1.ServerMessage
	31, // [31:32] is the sub-list for method output_type
	30, // [30:31] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_tunnel_proto_init() }
func file_tunnel_proto_init() {
	if File_tunnel_proto != nil {
		return
	}
	file_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerMessage_Connected)(nil),
		(*ServerMessage_Operation)(nil),
		(*ServerMessage_Shutdown)(nil),
		(*ServerMessage_WorkspaceResult)(nil),
	}
	file_tunnel_proto_msgTypes[1].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Result)(nil),
		(*AgentMessage_Error)(nil),
		(*AgentMessage_Deregister)(nil),
		(*AgentMessage_WorkspaceCall)(nil),
	}
	file_tunnel_proto_msgTypes[6].OneofWrappers = []any{
		(*Operation_RunCommand)(nil),
		(*Operation_ListDirectory)(nil),
		(*Operation_ReadFile)(nil),
		(*Operation_WriteFile)(nil),
		(*Operation_DeleteFile)(nil),
		(*Operation_InvokeHarness)(nil),
	}
	file_tunnel_proto_msgTypes[13].OneofWrappers = []any{
		(*OperationResult_RunCommand)(nil),
		(*OperationResult_ListDirectory)(nil),
		(*OperationResult_ReadFile)(nil),
		(*OperationResult_WriteFile)(nil),
		(*OperationResult_DeleteFile)(nil),
		(*OperationResult_InvokeHarness)(nil),
	}
	file_tunnel_proto_msgTypes[22].OneofWrappers = []any{
		(*WorkspaceCall_ReadOpen)(nil),
		(*WorkspaceCall_WriteBegin)(nil),
		(*WorkspaceCall_WriteCommit)(nil),
	}
	file_tunnel_proto_msgTypes[26].OneofWrappers = []any{
		(*WorkspaceResult_ReadTarget)(nil),
		(*WorkspaceResult_WriteTarget)(nil),
		(*WorkspaceResult_Committed)(nil),
		(*WorkspaceResult_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tunnel_proto_rawDesc), len(file_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tunnel_proto_goTypes,
		DependencyIndexes: file_tunnel_proto_depIdxs,
		MessageInfos:      file_tunnel_proto_msgTypes,
	}.Build()
	File_tunnel_proto = out.File
	file_tunnel_proto_goTypes = nil
	file_tunnel_proto_depIdxs = nil
}
